### ISSUE TITLE
root_path is not propagated to versioned apps properly, breaking openapi docs

### ISSUE THREAD

**Issue by kosz85** [DeanWay/fastapi-versioning#50]
My app is behind some proxy so it's url is smth like `http://abc.cd/some/path/v1_0/` to support it properly I'm adding `root_path="/some/path"`, and in general everything is working ok as in most cases this param is just ignored, except openapidocs, where it's used to generate path to `openapi.json`:

 `http://abc.cd/some/path/v1_0/docs`
```javascript
    const ui = SwaggerUIBundle({
        url: '/v1_0/openapi.json',
```
should be:
```javascript
    const ui = SwaggerUIBundle({
        url: '/some/path/v1_0/openapi.json',
```

**Comment by DeanWay** [comment]
fixed in version 0.10.0

**Comment by nierw** [comment]
Still experiencing this in 0.10.0

**Comment by DeanWay** [comment]
@nierw can you include steps to reproduce? And specifically how this is different in a real world scenario than in https://github.com/DeanWay/fastapi-versioning/tree/master/example/proxy
Thanks

**Comment by nierw** [comment]
@DeanWay So it looks as if I misread the changes, apologies - I fixed my end. However the core problem is that `root_path` has to be passed directly to `VersionedFastAPI` instead of being propagated from the underlying `FastAPI` object. This is a bit unclear without directly reading the examples. Additionally this is a breaking change for certain codebases that rely on operations prior to creation of `VersionedFastAPI` instances.

Defining `root_path` from the root `FastAPI` object should be a possible, if not the preferred way to deal with this param.
https://github.com/DeanWay/fastapi-versioning/blob/master/example/proxy/app.py#L5
